---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitchusapp
  namespace: mynamespace-1432497
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: pitchucontainer
        image: pitchunath/webapp:latest
        ports:
        - containerPort: 8080

---


apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: mynamespace-1432497
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: myapp
